# Generated by Django 4.2 on 2024-04-10 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuladorprueba',
            name='fecha_registro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
