# Generated by Django 4.2 on 2024-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0038_alter_registropagosmodelmanual_simulador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagosmodel',
            name='simulador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
