# Generated by Django 4.2 on 2024-04-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_dato'),
        ('calificaciones', '0039_alter_registropagosmodel_simulador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagosmodel',
            name='simulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulador_unico', to='dashboard.simuladorprueba'),
        ),
    ]
